// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/CD3_2.gold"
import gold.*;
import gold.structures.*;
import gold.structures.automaton.*;
import gold.structures.bag.*;
import gold.structures.collection.*;
import gold.structures.deque.*;
import gold.structures.disjointset.*;
import gold.structures.graph.*;
import gold.structures.heap.*;
import gold.structures.list.*;
import gold.structures.map.*;
import gold.structures.multimap.*;
import gold.structures.point.*;
import gold.structures.queue.*;
import gold.structures.set.*;
import gold.structures.stack.*;
import gold.structures.tree.*;
import gold.structures.tree.binary.*;
import gold.structures.tree.nary.*;
import gold.structures.tuple.*;
import gold.structures.turingMachine.*;
import gold.swing.*;
import gold.swing.icon.*;
import gold.swing.icon.ajaxload.*;
import gold.swing.icon.famfamfam.*;
import gold.swing.icon.gold.*;
import gold.swing.icon.jlfgr.*;
import gold.swing.icon.wikimedia.*;
import gold.swing.icon.windows.*;
import gold.swing.look.*;
import gold.swing.util.*;
import gold.test.*;
import gold.test.automaton.*;
import gold.test.general.*;
import gold.test.graph.*;
import gold.util.*;
import gold.visualization.*;
import gold.visualization.automaton.*;
import gold.visualization.graph.*;
import gold.visualization.quadtree.*;
import gold.visualization.turingMachine.*;
import gold.visualization.util.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class CD3_2 {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static Object A=null;
  public static Object B=null;
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=28;
      java.util.Scanner sc=null;
      sc=$invokeConstructor(java.util.Scanner.class,new Object[]{$invokeField(System.class,"in",true,null)});
      $line=30;
      A=$fix($opIntvlY('a','z'));
      $line=31;
      B=$fix($opIntvlY('0','9'));
      $line=32;
      Object coder=$fix(CD3_2.createCoder());
      $line=33;
      Object deCoder=$fix(CD3_2.createDecoder());
      $line=40;
      CD3_2.testCodeDecode($cast(gold.structures.automaton.ITransducer.class,coder),$cast(gold.structures.automaton.ITransducer.class,deCoder));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,CD3_2.class,"main",$line);
    }
  }
  public static Object testCodeDecode(ITransducer C, ITransducer D) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=47;
      java.util.Scanner sc=null;
      sc=$invokeConstructor(java.util.Scanner.class,new Object[]{$invokeField(System.class,"in",true,null)});
      $line=51;
      System.out.println($message(new Object[]{"Testing Coder-Decoder"}));
      $line=52;
      Object string=$fix(" ");
      $line=53;
      while (true) {
        if (!(!$opEqualY(string,""))) break;
        $line=54;
        System.out.println($message(new Object[]{"----------------------------"}));
        $line=55;
        System.out.println($message(new Object[]{"Input string: (empty string to end)"}));
        $line=56;
        if (!$opEqualY(string,"")) {
          $line=58;
          string=$fix(((java.util.Scanner)sc).nextLine());
          $line=59;
          if (!$opEqualY(string,"")) {
            $line=61;
            Object option=$fix("");
            $line=62;
            while (true) {
              if (!(!$opMembrY(option,GCollections.asSet("1","2","3")))) break;
              $line=63;
              System.out.println($message(new Object[]{"What do you want to do?"}));
              $line=64;
              System.out.println($message(new Object[]{"1. code only?"}));
              $line=65;
              System.out.println($message(new Object[]{"2. code and decode?"}));
              $line=66;
              System.out.println($message(new Object[]{"3. decode only?"}));
              $line=68;
              option=$fix(((java.util.Scanner)sc).nextLine());
            }
            $line=70;
            Object stringOut=$fix("");
            $line=71;
            if (($opEqualY(option,"1")||$opEqualY(option,"2"))) {
              $line=72;
              Object result=$fix(((gold.structures.automaton.ITransducer)C).acceptsString($cast(java.lang.String.class,string)));
              $line=73;
              System.out.println($message(new Object[]{$opAdditY($opAdditY($opAdditY("The string was ",(($bool(result))?("accepted"):("not accepted"))),". Output: "),((gold.structures.automaton.ITransducer)C).getOutputString())}));
              $line=74;
              stringOut=$fix(((gold.structures.automaton.ITransducer)C).getOutputString());
              $line=75;
              if ($opEqualY(option,"2")) {
                $line=76;
                result=$fix(((gold.structures.automaton.ITransducer)D).acceptsString($cast(java.lang.String.class,stringOut)));
                $line=77;
                System.out.println($message(new Object[]{$opAdditY($opAdditY($opAdditY("The coded string was ",(($bool(result))?("accepted"):("not accepted"))),". Output: "),((gold.structures.automaton.ITransducer)D).getOutputString())}));
                $line=78;
                Object stringOut1=$fix(((gold.structures.automaton.ITransducer)D).getOutputString());
                $line=79;
                System.out.println($message(new Object[]{$opAdditY($opAdditY("The decoded string is ",((!$opEqualY(stringOut1,string))?("not "):(""))),"equal to the original string.")}));
              }
            }
            else {
              $line=83;
              Object result=$fix(((gold.structures.automaton.ITransducer)D).acceptsString($cast(java.lang.String.class,string)));
              $line=84;
              System.out.println($message(new Object[]{$opAdditY($opAdditY($opAdditY("The string was ",(($bool(result))?("accepted"):("not accepted")))," by the decoder. Output: "),((gold.structures.automaton.ITransducer)D).getOutputString())}));
            }
          }
        }
      }
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,CD3_2.class,"testCodeDecode",$line);
    }
    return $result;
  }
  public static ITransducer createCoder() {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=99;
      gold.structures.set.ISet $v1=$newSet();
      $v2:for (Object d:GCollections.unmodifiableCollection(GCollections.asSet(3,2,5))) {
        for (Object s:GCollections.unmodifiableCollection($opIntvlY('a','z'))) {
          int $v3=$int(0);
          int $v4=$int(5)-1;
          for (int pos=$v3; pos<=$v4; pos++) {
            $v1.add(GCollections.asList(d,s,pos));
          }
        }
      }
      Object Q=$fix($opUnionY($opUnionY($v1,GCollections.asSet(3,2,5,"I","E")),$opCartsY(new Object[]{GCollections.asSet(3,2,5),$opIntvlY('a','z')})));
      $line=101;
      Object \u03A3=$fix($opUnionY($opIntvlY('a','z'),GCollections.asSet(':','2','3','5')));
      $line=102;
      Object \u03A3_=$fix($opUnionY(\u03A3,GCollections.asSet('#')));
      $line=103;
      Object q_0=$fix("I");
      $line=104;
      gold.structures.set.ISet $v5=$newSet();
      $v6:for (Object d:GCollections.unmodifiableCollection(GCollections.asSet(3,2,5))) {
        for (Object s:GCollections.unmodifiableCollection($opIntvlY('a','z'))) {
          int $v7=$int(0);
          int $v8=$int(5)-1;
          for (int pos=$v7; pos<=$v8; pos++) {
            $v5.add(GCollections.asList(d,s,pos));
          }
        }
      }
      Object F=$fix($v5);
      $line=106;
      $result=$invokeConstructor(GDeterministicTransducer.class,new Object[]{Q,\u03A3,\u03A3_,q_0,F,new GMethod(CD3_2.class,"\u03B4"),new GMethod(CD3_2.class,"g"),new GMethod(CD3_2.class,"h")});
      if (true) break $try;
      $line=107;
      $rethrow(new RuntimeException("The function \"createCoder()\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,CD3_2.class,"createCoder",$line);
    }
    return $cast(ITransducer.class,$result);
  }
  public static Object \u03B4(Object state, Object input) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=114;
      if (($opEqualY(state,"I")&&$opMembrY(input,GCollections.asSet('2','3','5')))) {
        $line=114;
        $result=$opSubtrY(input,'0');
        if (true) break $try;
      }
      else {
        $line=115;
        if (($opMembrY(state,GCollections.asSet(2,3,5))&&$opMembrY(input,$opIntvlY('a','z')))) {
          $line=115;
          $result=GCollections.asList(state,input);
          if (true) break $try;
        }
        else {
          $line=116;
          if ($opMembrY(state,GCollections.asSet(2,3,5,"I","E"))) {
            $line=116;
            $result="E";
            if (true) break $try;
          }
          else {
            $line=117;
            if (($opEqualY($opAbsolY(state),2)&&$opEqualY(input,':'))) {
              $line=117;
              $result=GCollections.asList($getArrayValue(state,new Object[]{0}),$getArrayValue(state,new Object[]{1}),1);
              if (true) break $try;
            }
            else {
              $line=118;
              if (($opEqualY($opAbsolY(state),3)&&$opMembrY(input,$opIntvlY('a','z')))) {
                $line=119;
                Object $v9=$getArrayValue(state,new Object[]{0});
                Object $v10=$getArrayValue(state,new Object[]{1});
                Object $v11=$getArrayValue(state,new Object[]{2});
                Object d=$fix($v9);
                Object s=$fix($v10);
                Object pos=$fix($v11);
                $line=120;
                $result=GCollections.asList(d,s,$opModulY($opAdditY(pos,1),d));
                if (true) break $try;
              }
              else {
                $line=121;
                $result="E";
                if (true) break $try;
              }
            }
          }
        }
      }
      $line=124;
      $rethrow(new RuntimeException("The function \"\u03B4(state:Object,input:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,CD3_2.class,"\u03B4",$line);
    }
    return $result;
  }
  public static Object h(Object state, Object input) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=132;
      if (($opEqualY(state,"I")&&$opMembrY(input,GCollections.asSet('2','3','5')))) {
        $line=132;
        $result=input;
        if (true) break $try;
      }
      else {
        $line=133;
        if (($opMembrY(state,GCollections.asSet(2,3,5))&&$opMembrY(input,$opIntvlY('a','z')))) {
          $line=133;
          $result=input;
          if (true) break $try;
        }
        else {
          $line=134;
          if ($opMembrY(state,GCollections.asSet(2,3,5,"I","E"))) {
            $line=134;
            $result="";
            if (true) break $try;
          }
          else {
            $line=135;
            if (($opEqualY($opAbsolY(state),2)&&$opEqualY(input,':'))) {
              $line=135;
              $result=":";
              if (true) break $try;
            }
            else {
              $line=136;
              if (($opEqualY($opAbsolY(state),3)&&$opMembrY(input,$opIntvlY('a','z')))) {
                $line=137;
                Object $v12=$getArrayValue(state,new Object[]{0});
                Object $v13=$getArrayValue(state,new Object[]{1});
                Object $v14=$getArrayValue(state,new Object[]{2});
                Object d=$fix($v12);
                Object s=$fix($v13);
                Object pos=$fix($v14);
                $line=138;
                if (($opEqualY(0,pos)&&$opEqualY(input,s))) {
                  $line=138;
                  $result="#";
                  if (true) break $try;
                }
                else {
                  $line=139;
                  if ($opEqualY(pos,1)) {
                    $line=139;
                    $result=CD3_2.shiftSymbol(input,d);
                    if (true) break $try;
                  }
                  else {
                    $line=140;
                    $result=input;
                    if (true) break $try;
                  }
                }
              }
              else {
                $line=142;
                $result="";
                if (true) break $try;
              }
            }
          }
        }
      }
      $line=145;
      $rethrow(new RuntimeException("The function \"h(state:Object,input:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,CD3_2.class,"h",$line);
    }
    return $result;
  }
  public static Object g(Object s) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=152;
      $result="";
      if (true) break $try;
      $line=153;
      $rethrow(new RuntimeException("The function \"g(s:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,CD3_2.class,"g",$line);
    }
    return $result;
  }
  public static ITransducer createDecoder() {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=156;
      gold.structures.set.ISet $v15=$newSet();
      $v16:for (Object d:GCollections.unmodifiableCollection(GCollections.asSet(3,2,5))) {
        for (Object s:GCollections.unmodifiableCollection($opIntvlY('a','z'))) {
          for (Object pos:GCollections.unmodifiableCollection($opUnionY($opIntvlY(0,5),GCollections.asSet("_")))) {
            $v15.add(GCollections.asList(d,s,pos));
          }
        }
      }
      Object Q=$fix($opUnionY($v15,GCollections.asSet(3,2,5,"I","E")));
      $line=157;
      Object \u03A3_=$fix($opUnionY($opIntvlY('a','z'),GCollections.asSet(':','2','3','5')));
      $line=158;
      Object \u03A3=$fix($opUnionY(\u03A3_,GCollections.asSet('#')));
      $line=159;
      Object q_0=$fix("I");
      $line=160;
      gold.structures.set.ISet $v17=$newSet();
      $v18:for (Object d:GCollections.unmodifiableCollection(GCollections.asSet(3,2,5))) {
        for (Object s:GCollections.unmodifiableCollection($opIntvlY('a','z'))) {
          int $v19=$int(0);
          int $v20=$int(5)-1;
          for (int pos=$v19; pos<=$v20; pos++) {
            $v17.add(GCollections.asList(d,s,pos));
          }
        }
      }
      Object F=$fix($v17);
      $line=162;
      $result=$invokeConstructor(GDeterministicTransducer.class,new Object[]{Q,\u03A3,\u03A3_,q_0,F,new GMethod(CD3_2.class,"\u03B41"),new GMethod(CD3_2.class,"g"),new GMethod(CD3_2.class,"h1")});
      if (true) break $try;
      $line=163;
      $rethrow(new RuntimeException("The function \"createDecoder()\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,CD3_2.class,"createDecoder",$line);
    }
    return $cast(ITransducer.class,$result);
  }
  public static Object \u03B41(Object state, Object input) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=169;
      if (($opEqualY(state,"I")&&$opMembrY(input,GCollections.asSet('2','3','5')))) {
        $line=169;
        $result=$opSubtrY(input,'0');
        if (true) break $try;
      }
      else {
        $line=170;
        if (($opMembrY(state,GCollections.asSet(2,3,5))&&$opMembrY(input,$opIntvlY('a','z')))) {
          $line=170;
          $result=GCollections.asList(state,input,"_");
          if (true) break $try;
        }
        else {
          $line=171;
          $result="E";
          if (true) break $try;
        }
      }
      $line=173;
      $rethrow(new RuntimeException("The function \"\u03B41(state:Object,input:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,CD3_2.class,"\u03B41",$line);
    }
    return $result;
  }
  public static Object \u03B41(java.lang.Iterable $v21, Object input) {
    int $line=0;
    Object $result=null;
    $try:try {
      java.util.Iterator $v22=GCollections.unmodifiableCollection($v21).iterator();
      Object d=$v22.next();
      Object s=$v22.next();
      Object pos=$v22.next();
      $line=176;
      if (($opEqualY(pos,"_")&&$opEqualY(input,':'))) {
        $line=176;
        $result=GCollections.asList(d,s,1);
        if (true) break $try;
      }
      else {
        $line=177;
        if ($opEqualY(pos,"_")) {
          $line=177;
          $result="E";
          if (true) break $try;
        }
        else {
          $line=178;
          if (($opEqualY(input,'#')&&!$opEqualY(pos,0))) {
            $line=178;
            $result="E";
            if (true) break $try;
          }
          else {
            $line=179;
            if (($opEqualY(input,s)&&$opEqualY(pos,0))) {
              $line=179;
              $result="E";
              if (true) break $try;
            }
            else {
              $line=180;
              if ($opMembrY(input,$opUnionY($opIntvlY('a','z'),GCollections.asSet('#')))) {
                $line=180;
                $result=GCollections.asList(d,s,$opModulY($opAdditY(pos,1),d));
                if (true) break $try;
              }
              else {
                $line=181;
                $result="E";
                if (true) break $try;
              }
            }
          }
        }
      }
      $line=183;
      $rethrow(new RuntimeException("The function \"\u03B41(\u27E8d,s,pos\u27E9:java.lang.Iterable,input:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,CD3_2.class,"\u03B41",$line);
    }
    return $result;
  }
  public static Object h1(Object state, Object input) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=189;
      if (($opEqualY(state,"I")&&$opMembrY(input,GCollections.asSet('2','3','5')))) {
        $line=189;
        $result=$opSubtrY(input,'0');
        if (true) break $try;
      }
      else {
        $line=190;
        if (($opMembrY(state,GCollections.asSet(2,3,5))&&$opMembrY(input,$opIntvlY('a','z')))) {
          $line=190;
          $result=input;
          if (true) break $try;
        }
        else {
          $line=191;
          $result="";
          if (true) break $try;
        }
      }
      $line=193;
      $rethrow(new RuntimeException("The function \"h1(state:Object,input:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,CD3_2.class,"h1",$line);
    }
    return $result;
  }
  public static Object h1(java.lang.Iterable $v23, Object input) {
    int $line=0;
    Object $result=null;
    $try:try {
      java.util.Iterator $v24=GCollections.unmodifiableCollection($v23).iterator();
      Object d=$v24.next();
      Object s=$v24.next();
      Object pos=$v24.next();
      $line=196;
      if (($opEqualY(pos,"_")&&$opEqualY(input,':'))) {
        $line=196;
        $result=input;
        if (true) break $try;
      }
      else {
        $line=197;
        if (($opEqualY(input,'#')&&$opEqualY(pos,0))) {
          $line=197;
          $result=s;
          if (true) break $try;
        }
        else {
          $line=198;
          if (($opMembrY(input,$opIntvlY('a','z'))&&$opEqualY(pos,1))) {
            $line=198;
            $result=CD3_2.shiftSymbol(input,$opMinusY(d));
            if (true) break $try;
          }
          else {
            $line=199;
            if ($opMembrY(input,$opIntvlY('a','z'))) {
              $line=199;
              $result=input;
              if (true) break $try;
            }
            else {
              $line=200;
              $result="";
              if (true) break $try;
            }
          }
        }
      }
      $line=202;
      $rethrow(new RuntimeException("The function \"h1(\u27E8d,s,pos\u27E9:java.lang.Iterable,input:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,CD3_2.class,"h1",$line);
    }
    return $result;
  }
  public static Object shiftSymbol(Object symbol, Object shift) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=210;
      Character r=null;
      r=$defaultValue(Character.class);
      $line=212;
      if ($opMembrY(symbol,$opIntvlY('a','z'))) {
        $line=213;
        r=$cast(Character.class,$fix($opAdditY('a',$opModulY($opAdditY($opSubtrY(symbol,'a'),shift),26))));
      }
      else {
        $line=214;
        if ($opMembrY(symbol,$opIntvlY('A','Z'))) {
          $line=215;
          r=$cast(Character.class,$fix($opAdditY('A',$opModulY($opAdditY($opSubtrY(symbol,'A'),shift),26))));
        }
        else {
          $line=216;
          if ($opMembrY(symbol,$opIntvlY('0','9'))) {
            $line=217;
            r=$cast(Character.class,$fix($opAdditY('0',$opModulY($opAdditY($opSubtrY(symbol,'0'),shift),10))));
          }
          else {
            $line=218;
            r=$cast(Character.class,$fix(r));
          }
        }
      }
      $line=220;
      $result=r;
      if (true) break $try;
      $line=221;
      $rethrow(new RuntimeException("The function \"shiftSymbol(symbol:Object,shift:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,CD3_2.class,"shiftSymbol",$line);
    }
    return $result;
  }
}
