// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/inter1.gold"
import gold.structures.automaton.*;
import gold.util.*;
import gold.visualization.automaton.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class inter1 {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=8;
      Object Q=$fix(GCollections.asSet(GCollections.asList("A","a"),GCollections.asList("A","b"),GCollections.asList("B","a"),GCollections.asList("B","b")));
      $line=9;
      Object \u03A3=$fix(GCollections.asSet('0','1'));
      $line=10;
      Object q=$fix(GCollections.asList("A","a"));
      $line=11;
      Object F=$fix(GCollections.asSet(GCollections.asList("B","a")));
      $line=12;
      Object \u03B4=$fix(new Object[]{new Object[]{GCollections.asList("A","a"),'0',GCollections.asList("B","a")},new Object[]{GCollections.asList("B","a"),'0',GCollections.asList("A","a")},new Object[]{GCollections.asList("A","b"),'0',GCollections.asList("B","b")},new Object[]{GCollections.asList("B","b"),'0',GCollections.asList("A","b")},new Object[]{GCollections.asList("A","a"),'1',GCollections.asList("B","b")},new Object[]{GCollections.asList("B","b"),'1',GCollections.asList("A","a")},new Object[]{GCollections.asList("B","a"),'1',GCollections.asList("A","b")},new Object[]{GCollections.asList("A","b"),'1',GCollections.asList("B","a")}});
      $line=21;
      GDeterministicAutomaton A=$cast(GDeterministicAutomaton.class,$fix($invokeConstructor(GDeterministicAutomaton.class,new Object[]{Q,\u03A3,q,F,\u03B4})));
      $line=22;
      GAutomataFrame.show($cast(gold.structures.automaton.IAutomaton.class,A));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,inter1.class,"main",$line);
    }
  }
}
