// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/inter2.gold"
import gold.structures.automaton.*;
import gold.util.*;
import gold.visualization.automaton.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class inter2 {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=8;
      Object \u03A3=$fix(GCollections.asSet('0','1'));
      $line=10;
      Object Q1=$fix(GCollections.asSet("A","B"));
      $line=11;
      Object q1=$fix("A");
      $line=12;
      Object F1=$fix(GCollections.asSet("B"));
      $line=13;
      GDeterministicAutomaton A1=$cast(GDeterministicAutomaton.class,$fix($invokeConstructor(GDeterministicAutomaton.class,new Object[]{Q1,\u03A3,q1,F1,new GMethod(inter2.class,"\u03B41")})));
      $line=16;
      Object Q2=$fix(GCollections.asSet("a","b"));
      $line=17;
      Object q2=$fix("a");
      $line=18;
      Object F2=$fix(GCollections.asSet("a"));
      $line=19;
      GDeterministicAutomaton A2=$cast(GDeterministicAutomaton.class,$fix($invokeConstructor(GDeterministicAutomaton.class,new Object[]{Q2,\u03A3,q2,F2,new GMethod(inter2.class,"\u03B42")})));
      $line=20;
      GAutomataFrame frame=null;
      frame=$invokeConstructor(GAutomataFrame.class,new Object[]{});
      $line=21;
      $invokeMethod("display",frame,new Object[]{"A1",A1});
      $line=22;
      $invokeMethod("display",frame,new Object[]{"A2",A2});
      $line=23;
      ((gold.visualization.automaton.GAutomataFrame)frame).setVisible($bool(true));
      $line=27;
      gold.structures.set.ISet $v1=$newSet();
      $v2:for (Object a:GCollections.unmodifiableCollection(F1)) {
        for (Object b:GCollections.unmodifiableCollection(F2)) {
          $v1.add(GCollections.asList(a,b));
        }
      }
      Object F=$fix($v1);
      $line=28;
      GDeterministicAutomaton A=$cast(GDeterministicAutomaton.class,$fix($invokeConstructor(GDeterministicAutomaton.class,new Object[]{$opCartsY(new Object[]{Q1,Q2}),\u03A3,GCollections.asList(q1,q2),F,new GMethod(inter2.class,"\u03B4")})));
      $line=29;
      GAutomataFrame.show($cast(gold.structures.automaton.IAutomaton.class,A));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,inter2.class,"main",$line);
    }
  }
  public static Object \u03B4(java.lang.Iterable $v3, Object s) {
    int $line=0;
    Object $result=null;
    $try:try {
      java.util.Iterator $v4=GCollections.unmodifiableCollection($v3).iterator();
      Object p=$v4.next();
      Object q=$v4.next();
      $line=51;
      $result=GCollections.asList(inter2.\u03B41(p,s),inter2.\u03B42(q,s));
      if (true) break $try;
      $line=52;
      $rethrow(new RuntimeException("The function \"\u03B4(\u27E8p,q\u27E9:java.lang.Iterable,s:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,inter2.class,"\u03B4",$line);
    }
    return $result;
  }
  public static Object \u03B41(Object q, Object s) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=55;
      if ($opEqualY(q,"A")) {
        $line=56;
        $result="B";
        if (true) break $try;
      }
      else {
        $line=58;
        $result="A";
        if (true) break $try;
      }
      $line=60;
      $rethrow(new RuntimeException("The function \"\u03B41(q:Object,s:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,inter2.class,"\u03B41",$line);
    }
    return $result;
  }
  public static Object \u03B42(Object q, Object s) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=63;
      if (($opEqualY(s,'1')&&$opEqualY(q,"a"))) {
        $line=64;
        $result="b";
        if (true) break $try;
      }
      else {
        $line=65;
        if (($opEqualY(s,'1')&&$opEqualY(q,"b"))) {
          $line=66;
          $result="a";
          if (true) break $try;
        }
        else {
          $line=68;
          $result=q;
          if (true) break $try;
        }
      }
      $line=70;
      $rethrow(new RuntimeException("The function \"\u03B42(q:Object,s:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,inter2.class,"\u03B42",$line);
    }
    return $result;
  }
}
