// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/Lexer_logo.gold"
import gold.structures.automaton.*;
import gold.util.*;
import gold.visualization.automaton.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class Lexer_logo {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=22;
      Object Q=$fix(GCollections.asSet("A","B","C","D","E","F","G","H","O"));
      $line=23;
      Object \u03A3=$fix($opUnionY($opUnionY($opIntvlY('A','Z'),$opIntvlY('0','9')),GCollections.asSet('[',']','.',' ','+','-','*','/','"','<','>','=')));
      $line=24;
      Object \u0393=$fix(GCollections.asSet('D','F','R','P','L','U','N','M','O','[',']'));
      $line=25;
      Object q=$fix("A");
      $line=26;
      Object F=$fix(GCollections.asSet("A"));
      $line=28;
      Object A=$fix($invokeConstructor(GDeterministicTransducer.class,new Object[]{Q,\u03A3,\u0393,q,F,new GMethod(Lexer_logo.class,"\u03B4"),new GMethod(Lexer_logo.class,"g"),new GMethod(Lexer_logo.class,"h")}));
      $line=29;
      GAutomataFrame.show($cast(gold.structures.automaton.IAutomaton.class,A));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Lexer_logo.class,"main",$line);
    }
  }
  public static Object \u03B4(Object q, Object \u03C3) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=33;
      if ($opEqualY(q,"A")) {
        $line=34;
        if ($opEqualY(\u03C3,'P')) {
          $line=35;
          $result="B";
          if (true) break $try;
        }
        else {
          $line=36;
          if ($bool(($opEqualY(\u03C3,'F')||$opEqualY(\u03C3,'L')))) {
            $line=37;
            $result="F";
            if (true) break $try;
          }
          else {
            $line=38;
            if ($opEqualY(\u03C3,'R')) {
              $line=39;
              $result="D";
              if (true) break $try;
            }
            else {
              $line=40;
              if ($opEqualY(\u03C3,'M')) {
                $line=41;
                $result="H";
                if (true) break $try;
              }
              else {
                $line=43;
                $result="A";
                if (true) break $try;
              }
            }
          }
        }
      }
      else {
        $line=45;
        if ($opEqualY(q,"B")) {
          $line=46;
          if ($bool(($opEqualY(\u03C3,'D')||$opEqualY(\u03C3,'U')))) {
            $line=47;
            $result="C";
            if (true) break $try;
          }
          else {
            $line=49;
            $result="B";
            if (true) break $try;
          }
        }
        else {
          $line=51;
          if ($opEqualY(q,"C")) {
            $line=52;
            if ($opEqualY(\u03C3,'.')) {
              $line=53;
              $result="A";
              if (true) break $try;
            }
            else {
              $line=55;
              $result="C";
              if (true) break $try;
            }
          }
          else {
            $line=57;
            if ($opEqualY(q,"D")) {
              $line=58;
              if ($opEqualY(\u03C3,'E')) {
                $line=59;
                $result="E";
                if (true) break $try;
              }
              else {
                $line=61;
                $result="F";
                if (true) break $try;
              }
            }
            else {
              $line=63;
              if ($opEqualY(q,"E")) {
                $line=64;
                if ($bool(((((((((($opEqualY(\u03C3,'0')||$opEqualY(\u03C3,'1'))||$opEqualY(\u03C3,'2'))||$opEqualY(\u03C3,'3'))||$opEqualY(\u03C3,'4'))||$opEqualY(\u03C3,'5'))||$opEqualY(\u03C3,'6'))||$opEqualY(\u03C3,'7'))||$opEqualY(\u03C3,'8'))||$opEqualY(\u03C3,'9')))) {
                  $line=65;
                  $result="G";
                  if (true) break $try;
                }
                else {
                  $line=67;
                  $result="E";
                  if (true) break $try;
                }
              }
              else {
                $line=69;
                if ($opEqualY(q,"F")) {
                  $line=70;
                  if ($bool(((((((((($opEqualY(\u03C3,'0')||$opEqualY(\u03C3,'1'))||$opEqualY(\u03C3,'2'))||$opEqualY(\u03C3,'3'))||$opEqualY(\u03C3,'4'))||$opEqualY(\u03C3,'5'))||$opEqualY(\u03C3,'6'))||$opEqualY(\u03C3,'7'))||$opEqualY(\u03C3,'8'))||$opEqualY(\u03C3,'9')))) {
                    $line=71;
                    $result="G";
                    if (true) break $try;
                  }
                  else {
                    $line=73;
                    $result="F";
                    if (true) break $try;
                  }
                }
                else {
                  $line=75;
                  if ($opEqualY(q,"H")) {
                    $line=76;
                    if ($bool(((((((((($opEqualY(\u03C3,'0')||$opEqualY(\u03C3,'1'))||$opEqualY(\u03C3,'2'))||$opEqualY(\u03C3,'3'))||$opEqualY(\u03C3,'4'))||$opEqualY(\u03C3,'5'))||$opEqualY(\u03C3,'6'))||$opEqualY(\u03C3,'7'))||$opEqualY(\u03C3,'8'))||$opEqualY(\u03C3,'9')))) {
                      $line=77;
                      $result="G";
                      if (true) break $try;
                    }
                    else {
                      $line=79;
                      $result="H";
                      if (true) break $try;
                    }
                  }
                  else {
                    $line=81;
                    if ($opEqualY(q,"O")) {
                      $line=82;
                      if ($bool(((((((((($opEqualY(\u03C3,'0')||$opEqualY(\u03C3,'1'))||$opEqualY(\u03C3,'2'))||$opEqualY(\u03C3,'3'))||$opEqualY(\u03C3,'4'))||$opEqualY(\u03C3,'5'))||$opEqualY(\u03C3,'6'))||$opEqualY(\u03C3,'7'))||$opEqualY(\u03C3,'8'))||$opEqualY(\u03C3,'9')))) {
                        $line=83;
                        $result="G";
                        if (true) break $try;
                      }
                      else {
                        $line=85;
                        $result="O";
                        if (true) break $try;
                      }
                    }
                    else {
                      $line=88;
                      if ($bool(($opEqualY(\u03C3,'.')||$opEqualY(\u03C3,'[')))) {
                        $line=89;
                        $result="A";
                        if (true) break $try;
                      }
                      else {
                        $line=90;
                        if ($bool((((((($opEqualY(\u03C3,'+')||$opEqualY(\u03C3,'-'))||$opEqualY(\u03C3,'*'))||$opEqualY(\u03C3,'/'))||$opEqualY(\u03C3,'='))||$opEqualY(\u03C3,'<'))||$opEqualY(\u03C3,'>')))) {
                          $line=91;
                          $result="O";
                          if (true) break $try;
                        }
                        else {
                          $line=93;
                          $result="G";
                          if (true) break $try;
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
      $line=96;
      $rethrow(new RuntimeException("The function \"\u03B4(q:Object,\u03C3:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Lexer_logo.class,"\u03B4",$line);
    }
    return $result;
  }
  public static Object g(Object q) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=99;
      $result="";
      if (true) break $try;
      $line=100;
      $rethrow(new RuntimeException("The function \"g(q:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Lexer_logo.class,"g",$line);
    }
    return $result;
  }
  public static Object h(Object q, Object \u03C3) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=104;
      if ($opEqualY(q,"A")) {
        $line=105;
        if ($opEqualY(\u03C3,'P')) {
          $line=106;
          $result="";
          if (true) break $try;
        }
        else {
          $line=107;
          if ($opEqualY(\u03C3,'F')) {
            $line=108;
            $result='F';
            if (true) break $try;
          }
          else {
            $line=109;
            if ($opEqualY(\u03C3,'L')) {
              $line=110;
              $result='L';
              if (true) break $try;
            }
            else {
              $line=111;
              if ($opEqualY(\u03C3,'R')) {
                $line=112;
                $result="";
                if (true) break $try;
              }
              else {
                $line=113;
                if ($opEqualY(\u03C3,']')) {
                  $line=114;
                  $result=']';
                  if (true) break $try;
                }
                else {
                  $line=115;
                  if ($opEqualY(\u03C3,'M')) {
                    $line=116;
                    $result='M';
                    if (true) break $try;
                  }
                  else {
                    $line=118;
                    $result="";
                    if (true) break $try;
                  }
                }
              }
            }
          }
        }
      }
      else {
        $line=120;
        if ($opEqualY(q,"B")) {
          $line=121;
          if ($opEqualY(\u03C3,'D')) {
            $line=122;
            $result='D';
            if (true) break $try;
          }
          else {
            $line=123;
            if ($opEqualY(\u03C3,'U')) {
              $line=124;
              $result='U';
              if (true) break $try;
            }
            else {
              $line=126;
              $result="";
              if (true) break $try;
            }
          }
        }
        else {
          $line=128;
          if ($opEqualY(q,"C")) {
            $line=129;
            $result="";
            if (true) break $try;
          }
          else {
            $line=130;
            if ($opEqualY(q,"D")) {
              $line=131;
              if ($opEqualY(\u03C3,'E')) {
                $line=132;
                $result='P';
                if (true) break $try;
              }
              else {
                $line=134;
                $result='R';
                if (true) break $try;
              }
            }
            else {
              $line=136;
              if ($opEqualY(q,"E")) {
                $line=137;
                if ($bool(((((((((($opEqualY(\u03C3,'0')||$opEqualY(\u03C3,'1'))||$opEqualY(\u03C3,'2'))||$opEqualY(\u03C3,'3'))||$opEqualY(\u03C3,'4'))||$opEqualY(\u03C3,'5'))||$opEqualY(\u03C3,'6'))||$opEqualY(\u03C3,'7'))||$opEqualY(\u03C3,'8'))||$opEqualY(\u03C3,'9')))) {
                  $line=138;
                  $result='N';
                  if (true) break $try;
                }
                else {
                  $line=140;
                  $result="";
                  if (true) break $try;
                }
              }
              else {
                $line=142;
                if ($opEqualY(q,"F")) {
                  $line=143;
                  if ($bool(((((((((($opEqualY(\u03C3,'0')||$opEqualY(\u03C3,'1'))||$opEqualY(\u03C3,'2'))||$opEqualY(\u03C3,'3'))||$opEqualY(\u03C3,'4'))||$opEqualY(\u03C3,'5'))||$opEqualY(\u03C3,'6'))||$opEqualY(\u03C3,'7'))||$opEqualY(\u03C3,'8'))||$opEqualY(\u03C3,'9')))) {
                    $line=144;
                    $result='N';
                    if (true) break $try;
                  }
                  else {
                    $line=146;
                    $result="";
                    if (true) break $try;
                  }
                }
                else {
                  $line=148;
                  if ($opEqualY(q,"H")) {
                    $line=149;
                    if ($bool(((((((((($opEqualY(\u03C3,'0')||$opEqualY(\u03C3,'1'))||$opEqualY(\u03C3,'2'))||$opEqualY(\u03C3,'3'))||$opEqualY(\u03C3,'4'))||$opEqualY(\u03C3,'5'))||$opEqualY(\u03C3,'6'))||$opEqualY(\u03C3,'7'))||$opEqualY(\u03C3,'8'))||$opEqualY(\u03C3,'9')))) {
                      $line=150;
                      $result='N';
                      if (true) break $try;
                    }
                    else {
                      $line=152;
                      $result="";
                      if (true) break $try;
                    }
                  }
                  else {
                    $line=154;
                    if ($opEqualY(q,"O")) {
                      $line=155;
                      if ($bool(((((((((($opEqualY(\u03C3,'0')||$opEqualY(\u03C3,'1'))||$opEqualY(\u03C3,'2'))||$opEqualY(\u03C3,'3'))||$opEqualY(\u03C3,'4'))||$opEqualY(\u03C3,'5'))||$opEqualY(\u03C3,'6'))||$opEqualY(\u03C3,'7'))||$opEqualY(\u03C3,'8'))||$opEqualY(\u03C3,'9')))) {
                        $line=156;
                        $result='N';
                        if (true) break $try;
                      }
                      else {
                        $line=158;
                        $result="";
                        if (true) break $try;
                      }
                    }
                    else {
                      $line=161;
                      if ($opEqualY(\u03C3,'[')) {
                        $line=162;
                        $result='[';
                        if (true) break $try;
                      }
                      else {
                        $line=163;
                        if ($bool((((((($opEqualY(\u03C3,'+')||$opEqualY(\u03C3,'-'))||$opEqualY(\u03C3,'*'))||$opEqualY(\u03C3,'/'))||$opEqualY(\u03C3,'='))||$opEqualY(\u03C3,'<'))||$opEqualY(\u03C3,'>')))) {
                          $line=164;
                          $result='O';
                          if (true) break $try;
                        }
                        else {
                          $line=166;
                          $result="";
                          if (true) break $try;
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
      $line=169;
      $rethrow(new RuntimeException("The function \"h(q:Object,\u03C3:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,Lexer_logo.class,"h",$line);
    }
    return $result;
  }
}
