// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/mealy_bin_2_dec.gold"
import gold.structures.automaton.*;
import gold.util.*;
import gold.visualization.automaton.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class mealy_bin_2_dec {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=16;
      Object M=$fix(mealy_bin_2_dec.createTransducer());
      $line=17;
      GAutomataFrame.show($cast(gold.structures.automaton.IAutomaton.class,M));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,mealy_bin_2_dec.class,"main",$line);
    }
  }
  public static ITransducer createTransducer() {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=21;
      Object Q=$fix(GCollections.asSet("Init",'0','1'));
      $line=22;
      Object \u03A3=$fix(GCollections.asSet('0','1'));
      $line=23;
      Object \u0393=$fix($opIntvlY('0','3'));
      $line=24;
      Object q0=$fix("Init");
      $line=25;
      Object F=$fix(GCollections.asSet("Init"));
      $line=26;
      $result=$invokeConstructor(GDeterministicTransducer.class,new Object[]{Q,\u03A3,\u0393,q0,F,new GMethod(mealy_bin_2_dec.class,"\u03B4"),new GMethod(mealy_bin_2_dec.class,"g"),new GMethod(mealy_bin_2_dec.class,"h")});
      if (true) break $try;
      $line=27;
      $rethrow(new RuntimeException("The function \"createTransducer()\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,mealy_bin_2_dec.class,"createTransducer",$line);
    }
    return $cast(ITransducer.class,$result);
  }
  public static Object \u03B4(Object q, Object \u03C3) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=30;
      if ($opEqualY(q,"Init")) {
        $line=31;
        $result=\u03C3;
        if (true) break $try;
      }
      else {
        $line=33;
        $result="Init";
        if (true) break $try;
      }
      $line=35;
      $rethrow(new RuntimeException("The function \"\u03B4(q:Object,\u03C3:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,mealy_bin_2_dec.class,"\u03B4",$line);
    }
    return $result;
  }
  public static Object h(Object q, Object \u03C3) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=38;
      if ($opEqualY(q,"Init")) {
        $line=39;
        $result="";
        if (true) break $try;
      }
      else {
        $line=41;
        $result=$opAdditY($opMultpY($opSubtrY(q,'0'),2),$opSubtrY(\u03C3,'0'));
        if (true) break $try;
      }
      $line=44;
      $rethrow(new RuntimeException("The function \"h(q:Object,\u03C3:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,mealy_bin_2_dec.class,"h",$line);
    }
    return $result;
  }
  public static Object g(Object q) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=47;
      $result="";
      if (true) break $try;
      $line=48;
      $rethrow(new RuntimeException("The function \"g(q:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,mealy_bin_2_dec.class,"g",$line);
    }
    return $result;
  }
}
