// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/mealy.gold"
import gold.structures.automaton.*;
import gold.util.*;
import gold.visualization.automaton.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class mealy {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=5;
      Object Q=$fix(GCollections.asSet("A","D","E"));
      $line=6;
      Object \u03A3=$fix(GCollections.asSet('0','1'));
      $line=7;
      Object \u0393=$fix(GCollections.asSet('0','1'));
      $line=8;
      Object q=$fix("A");
      $line=9;
      Object F=$fix(GCollections.asSet("A"));
      $line=11;
      Object A=$fix($invokeConstructor(GDeterministicTransducer.class,new Object[]{Q,\u03A3,\u0393,q,F,new GMethod(mealy.class,"\u03B4"),new GMethod(mealy.class,"g"),new GMethod(mealy.class,"h")}));
      $line=12;
      GAutomataFrame.show($cast(gold.structures.automaton.IAutomaton.class,A));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,mealy.class,"main",$line);
    }
  }
  public static Object \u03B4(Object q, Object \u03C3) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=16;
      if ($opEqualY(q,"A")) {
        $line=17;
        if ($opEqualY(\u03C3,'1')) {
          $line=18;
          $result="E";
          if (true) break $try;
        }
        else {
          $line=20;
          $result="D";
          if (true) break $try;
        }
      }
      else {
        $line=22;
        if ($opEqualY(q,"E")) {
          $line=23;
          if ($opEqualY(\u03C3,'1')) {
            $line=24;
            $result="E";
            if (true) break $try;
          }
          else {
            $line=26;
            $result="D";
            if (true) break $try;
          }
        }
        else {
          $line=29;
          if ($opEqualY(\u03C3,'1')) {
            $line=30;
            $result="A";
            if (true) break $try;
          }
          else {
            $line=32;
            $result="E";
            if (true) break $try;
          }
        }
      }
      $line=35;
      $rethrow(new RuntimeException("The function \"\u03B4(q:Object,\u03C3:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,mealy.class,"\u03B4",$line);
    }
    return $result;
  }
  public static Object g(Object q) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=38;
      $result="";
      if (true) break $try;
      $line=39;
      $rethrow(new RuntimeException("The function \"g(q:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,mealy.class,"g",$line);
    }
    return $result;
  }
  public static Object h(Object q, Object \u03C3) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=43;
      if ($opEqualY(q,"A")) {
        $line=44;
        $result='1';
        if (true) break $try;
      }
      else {
        $line=45;
        if ($opEqualY(q,"E")) {
          $line=46;
          if ($opEqualY(\u03C3,'1')) {
            $line=47;
            $result='0';
            if (true) break $try;
          }
          else {
            $line=49;
            $result='1';
            if (true) break $try;
          }
        }
        else {
          $line=52;
          $result=\u03C3;
          if (true) break $try;
        }
      }
      $line=54;
      $rethrow(new RuntimeException("The function \"h(q:Object,\u03C3:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,mealy.class,"h",$line);
    }
    return $result;
  }
}
