// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/regex.gold"
import gold.structures.automaton.*;
import gold.util.*;
import gold.visualization.automaton.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class regex {
  static {
    gold.swing.util.GUtilities.installGoldLookAndFeel();
  }
  public static void main(String[] args) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=6;
      Object Q=$fix(GCollections.asSet("A","B","C","S","D","Err"));
      $line=7;
      Object \u03A3=$fix(GCollections.asSet('a','b','c'));
      $line=8;
      Object q=$fix("S");
      $line=9;
      Object F=$fix(GCollections.asSet("C","D"));
      $line=10;
      Object \u03B4=$fix(new Object[]{new Object[]{"S",'a',"S"},new Object[]{"S",'b',"A"},new Object[]{"A",'a',"A"},new Object[]{"A",'c',"Err"},new Object[]{"A",'b',"C"},new Object[]{"C",'a',"C"},new Object[]{"C",'b',"Err"},new Object[]{"C",'c',"Err"},new Object[]{"S",'c',"B"},new Object[]{"B",'a',"D"},new Object[]{"B",'c',"Err"},new Object[]{"B",'b',"Err"},new Object[]{"D",'a',"D"},new Object[]{"D",'b',"Err"},new Object[]{"D",'c',"Err"},new Object[]{"Err",'a',"Err"},new Object[]{"Err",'b',"Err"},new Object[]{"Err",'c',"Err"}});
      $line=30;
      GDeterministicAutomaton A=$cast(GDeterministicAutomaton.class,$fix($invokeConstructor(GDeterministicAutomaton.class,new Object[]{Q,\u03A3,q,F,\u03B4})));
      $line=31;
      GAutomataFrame.show($cast(gold.structures.automaton.IAutomaton.class,A));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,regex.class,"main",$line);
    }
  }
}
